const fs = require('fs');
const path = require('path');

const writeFiles = (files) => {
  Object.entries(files).forEach(([filePath, content]) => {
    const fullPath = path.resolve(__dirname, filePath);
    const dir = path.dirname(fullPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(fullPath, content.trim(), 'utf8');
  });
};

const files = {
  "frontend/src/pages/ai/AIAssistant.jsx": `
import React, { useState } from 'react';
import { Card, CardContent } from '../../components/ui/Card';
import { Input } from '../../components/ui/Input';
import { Button } from '../../components/ui/Button';
import { AIChatBubble } from '../../components/ui/AIChatBubble';
import { Send, Bot, Trash2 } from 'lucide-react';
import { mockAIAssistantChat } from '../../mocks';

export default function AIAssistant() {
  const [chat, setChat] = useState(mockAIAssistantChat);
  const [input, setInput] = useState('');

  const handleSend = () => {
    if (!input.trim()) return;
    setChat([...chat, { id: Date.now(), role: 'user', content: input }]);
    setInput('');
    setTimeout(() => {
      setChat(prev => [...prev, { id: Date.now()+1, role: 'ai', content: 'I am a mock AI. I cannot actually answer this right now, but I will in Phase 4!' }]);
    }, 1000);
  };

  return (
    <div className="h-[calc(100vh-8rem)] flex flex-col space-y-4">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-white flex items-center gap-2"><Bot /> Career Mentor AI</h1>
          <p className="text-gray-500 dark:text-gray-400">Ask any technical, HR, or career related questions.</p>
        </div>
        <Button variant="outline" size="sm" onClick={() => setChat([])}><Trash2 size={16} className="mr-2"/> Clear Chat</Button>
      </div>

      <Card className="flex-1 flex flex-col overflow-hidden bg-gray-50 dark:bg-gray-950/50">
        <CardContent className="flex-1 overflow-y-auto p-4 space-y-4">
          {chat.map(msg => (
            <div key={msg.id} className={\`flex \${msg.role === 'user' ? 'justify-end' : 'justify-start'}\`}>
              <div className="max-w-[80%]">
                {msg.role === 'user' ? (
                  <div className="bg-indigo-600 text-white p-3 rounded-2xl rounded-tr-sm text-sm">
                    {msg.content}
                  </div>
                ) : (
                  <AIChatBubble isUser={false} message={msg.content} />
                )}
              </div>
            </div>
          ))}
        </CardContent>
        <div className="p-4 bg-white dark:bg-gray-900 border-t dark:border-gray-800">
          <form className="flex gap-2" onSubmit={e => { e.preventDefault(); handleSend(); }}>
            <Input className="flex-1" placeholder="Type your question..." value={input} onChange={e => setInput(e.target.value)} />
            <Button type="submit" className="bg-indigo-600 text-white"><Send size={18} /></Button>
          </form>
        </div>
      </Card>
    </div>
  );
}
  `,
  "frontend/src/pages/ai/AIStudyPlanner.jsx": `
import React from 'react';
import { Card, CardHeader, CardTitle, CardContent } from '../../components/ui/Card';
import { Progress } from '../../components/ui/Progress';
import { AIChatBubble } from '../../components/ui/AIChatBubble';
import { mockAIStudyPlanner } from '../../mocks';
import { CheckSquare, Square } from 'lucide-react';

export default function AIStudyPlanner() {
  const plan = mockAIStudyPlanner;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-white flex items-center gap-2">Study Planner</h1>
        <p className="text-gray-500 dark:text-gray-400">Personalized weekly schedule generated by AI.</p>
      </div>

      <Card>
        <CardHeader>
          <div className="flex justify-between items-center">
            <CardTitle>{plan.week} Goal: {plan.goal}</CardTitle>
            <span className="font-bold text-indigo-600 dark:text-indigo-400">{plan.progress}% Completed</span>
          </div>
          <Progress value={plan.progress} className="h-2 mt-4" />
        </CardHeader>
        <CardContent className="space-y-6">
          <AIChatBubble isUser={false} message={plan.recommendations} />
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {plan.dailyPlan.map((day, i) => (
              <Card key={i} className="bg-gray-50 dark:bg-gray-900/50">
                <CardHeader className="pb-2"><CardTitle className="text-md">{day.day}</CardTitle></CardHeader>
                <CardContent className="space-y-2">
                  {day.tasks.map((task, j) => (
                    <div key={j} className="flex items-start gap-2 text-sm text-gray-700 dark:text-gray-300">
                      {day.completed ? <CheckSquare size={16} className="text-emerald-500 mt-0.5" /> : <Square size={16} className="text-gray-400 mt-0.5" />}
                      <span>{task}</span>
                    </div>
                  ))}
                </CardContent>
              </Card>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
  `,
  "frontend/src/pages/ai/AIMockInterview.jsx": `
import React from 'react';
import { Card, CardHeader, CardTitle, CardContent } from '../../components/ui/Card';
import { Button } from '../../components/ui/Button';
import { AIChatBubble } from '../../components/ui/AIChatBubble';
import { mockAIMockInterview } from '../../mocks';

export default function AIMockInterview() {
  const interview = mockAIMockInterview;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-white">AI Mock Interview</h1>
        <p className="text-gray-500 dark:text-gray-400">Practice real interview scenarios with voice/text feedback.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="md:col-span-2 space-y-6">
          <Card>
            <CardHeader><CardTitle>Interview Simulator</CardTitle></CardHeader>
            <CardContent className="flex flex-col items-center justify-center py-12 space-y-6">
              <div className="w-24 h-24 rounded-full bg-indigo-100 dark:bg-indigo-900/50 flex items-center justify-center animate-pulse">
                <span className="text-4xl">🎙️</span>
              </div>
              <p className="text-lg font-medium text-center">"Tell me about a time you had to optimize a complex circuit design."</p>
              <div className="flex gap-4">
                <Button className="bg-red-500 hover:bg-red-600 text-white">Stop Recording</Button>
                <Button variant="outline">Type Answer Instead</Button>
              </div>
            </CardContent>
          </Card>
        </div>
        
        <div className="space-y-6">
          <Card>
            <CardHeader><CardTitle>Last Interview Feedback</CardTitle></CardHeader>
            <CardContent className="space-y-4">
              <div className="flex justify-between items-center pb-4 border-b dark:border-gray-800">
                <span className="text-gray-500">Overall Score</span>
                <span className="text-2xl font-bold text-emerald-500">{interview.score}/100</span>
              </div>
              <AIChatBubble isUser={false} message={interview.feedback} />
              <div className="bg-amber-50 dark:bg-amber-900/10 p-3 rounded-md text-sm text-amber-800 dark:text-amber-300">
                <span className="font-bold">Focus Area: </span> {interview.improvement}
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
  `,
  "frontend/src/pages/ai/AIResumeReview.jsx": `
import React from 'react';
import { Link } from 'react-router-dom';
import { Card, CardContent } from '../../components/ui/Card';
import { Button } from '../../components/ui/Button';

export default function AIResumeReview() {
  return (
    <div className="flex flex-col items-center justify-center py-20 space-y-6 text-center">
      <h1 className="text-4xl font-bold tracking-tight text-gray-900 dark:text-white">AI Resume Review</h1>
      <p className="text-gray-500 dark:text-gray-400 max-w-md">Our AI Resume Review system is integrated directly into the Resume Builder as the ATS Report feature.</p>
      <Button asChild className="bg-indigo-600 text-white"><Link to="/resume/ats">Go to ATS Report</Link></Button>
    </div>
  );
}
  `
};

writeFiles(files);
console.log('Batch D - AI Pages generated.');
