import { Card, CardHeader, CardTitle, CardContent } from '../../components/ui/Card';
import { Progress } from '../../components/ui/Progress';
import { AIChatBubble } from '../../components/ui/AIChatBubble';
import { mockAIStudyPlanner } from '../../mocks';
import { CheckSquare, Square } from 'lucide-react';

export default function AIStudyPlanner() {
  const plan = mockAIStudyPlanner;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-white flex items-center gap-2">Study Planner</h1>
        <p className="text-gray-500 dark:text-gray-400">Personalized weekly schedule generated by AI.</p>
      </div>

      <Card>
        <CardHeader>
          <div className="flex justify-between items-center">
            <CardTitle>{plan.week} Goal: {plan.goal}</CardTitle>
            <span className="font-bold text-indigo-600 dark:text-indigo-400">{plan.progress}% Completed</span>
          </div>
          <Progress value={plan.progress} className="h-2 mt-4" />
        </CardHeader>
        <CardContent className="space-y-6">
          <AIChatBubble isUser={false} message={plan.recommendations} />
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {plan.dailyPlan.map((day, i) => (
              <Card key={i} className="bg-gray-50 dark:bg-gray-900/50">
                <CardHeader className="pb-2"><CardTitle className="text-md">{day.day}</CardTitle></CardHeader>
                <CardContent className="space-y-2">
                  {day.tasks.map((task, j) => (
                    <div key={j} className="flex items-start gap-2 text-sm text-gray-700 dark:text-gray-300">
                      {day.completed ? <CheckSquare size={16} className="text-emerald-500 mt-0.5" /> : <Square size={16} className="text-gray-400 mt-0.5" />}
                      <span>{task}</span>
                    </div>
                  ))}
                </CardContent>
              </Card>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}